## 3.2. Creating NumPy Arrays

### 3.2.1 Using Array Method

In [1]:
import numpy as np
nums_list = [10,12,14,16,20]
nums_array = np.array(nums_list)
type(nums_array)

numpy.ndarray

In [3]:
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
nums_2d.shape                 

(3, 3)

### 3.2.2. Using Arange Method

In [6]:
nums_arr = np.arange(5,11)
print(nums_arr)

[ 5  6  7  8  9 10]


In [8]:
nums_arr = np.arange(5,12,2)
print(nums_arr)

[ 5  7  9 11]


### 3.2.3. Using Ones Method

In [10]:
ones_array = np.ones(6)
print(ones_array)

[1. 1. 1. 1. 1. 1.]


In [15]:
ones_array = np.ones((6,4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 3.2.4. Using Zeros Method

In [16]:
zeros_array = np.zeros(6)
print(zeros_array)

[0. 0. 0. 0. 0. 0.]


In [17]:
zeros_array = np.zeros((6,4))
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### 3.2.5. Using Eyes Method

In [18]:
eyes_array = np.eye(5)
print(eyes_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 3.2.6. Using Random Method

In [19]:
uniform_random = np.random.rand(4, 5)
print(uniform_random)

[[0.36728531 0.25376281 0.05039624 0.96432236 0.08579293]
 [0.29194804 0.93016399 0.88781312 0.50209692 0.63069239]
 [0.99952044 0.44384871 0.46041845 0.10246553 0.53461098]
 [0.75817916 0.36505441 0.01683344 0.9887365  0.21490949]]


In [20]:
normal_random = np.random.randn(4, 5)
print(uniform_random)

[[0.36728531 0.25376281 0.05039624 0.96432236 0.08579293]
 [0.29194804 0.93016399 0.88781312 0.50209692 0.63069239]
 [0.99952044 0.44384871 0.46041845 0.10246553 0.53461098]
 [0.75817916 0.36505441 0.01683344 0.9887365  0.21490949]]


In [21]:
integer_random = np.random.randint(10, 50, 5)
print(integer_random)

[25 49 21 35 17]


## 3.3. Reshaping a Numpy Array

In [26]:
uniform_random = np.random.rand(4, 6)
uniform_random = uniform_random.reshape(3, 8)
print(uniform_random)

[[0.37576967 0.5425328  0.56087883 0.35265748 0.19677258 0.65107479
  0.63287089 0.70649913]
 [0.47830882 0.3570451  0.82151482 0.09622735 0.1269332  0.65866216
  0.31875221 0.91781242]
 [0.89785438 0.47306848 0.58350797 0.4604004  0.62352155 0.88064432
  0.0859386  0.51918485]]


## 3.4. Array Indexing and Slicing in NumPy

In [52]:
s = np.arange(1,11)
print(s)

[ 1  2  3  4  5  6  7  8  9 10]


In [54]:
print(s[1])

2


In [55]:
print(s[1:9])

[2 3 4 5 6 7 8 9]


In [57]:
print(s[:5])
print(s[5:])

[1 2 3 4 5]
[ 6  7  8  9 10]


In [62]:
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
print(nums_2d[:2,:]) 

[[10 12 13]
 [45 32 16]]


In [63]:
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
print(nums_2d[:,:2]) 

[[10 12]
 [45 32]
 [45 32]]


In [65]:
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
print(nums_2d[1:,1:]) 

[[32 16]
 [32 16]]


## 3.5. NumPy for Arithmetic Operations

### 3.5.1. Finding Square Root

In [33]:
nums = [10,20,30,40,50]
np_sqr = np.sqrt(nums)
print(np_sqr)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


### 3.5.2. Finding Logs

In [34]:
nums = [10,20,30,40,50]
np_log = np.log(nums)
print(np_log )

[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


### 3.5.3. Finding Exponents

In [35]:
nums = [10,20,30,40,50]
np_exp = np.exp(nums)
print(np_exp)

[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]


### 3.5.4. Finding Sine and Cosine

In [36]:
nums = [10,20,30,40,50]
np_sine = np.sin(nums)
print(np_sine)

nums = [10,20,30,40,50]
np_cos = np.cos(nums)
print(np_cos)

[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]


## 3.6. NumPy for Linear Algebra Operations

### 3.6.1. Dot Product of Matrices

In [42]:
A = np.random.randn(4,5)

B = np.random.randn(5,4)

Z =  np.dot(A,B)

print(Z)

[[ 1.43837722 -4.74991285  1.42127048 -0.41569506]
 [-1.64613809  5.79380984 -1.33542482  1.53201023]
 [-1.31518878  0.72397674 -2.01300047  0.61651047]
 [-1.36765444  3.83694475 -0.56382045  0.21757162]]


### 3.6.2. Element-wise Matrix Multiplication

In [44]:
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
multiply = np.multiply(nums_2d, nums_2d)
print(multiply)

[[ 100  144  169]
 [2025 1024  256]
 [2025 1024  256]]


### 3.6.3. Finding Matrix Inverse

In [48]:
row1 = [1,2,3]
row2 = [4,5,6]
row3 = [7,8,9]

nums_2d = np.array([row1, row2, row3])

inverse = np.linalg.inv(nums_2d)
print(inverse)

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


### 3.6.4. Finding Matrix Determinant

In [51]:
row1 = [1,2,3]
row2 = [4,5,6]
row3 = [7,8,9]

nums_2d = np.array([row1, row2, row3])

determinant = np.linalg.det(nums_2d)
print(determinant)

-9.51619735392994e-16


### 3.6.5. Finding Matrix Trace

In [50]:
row1 = [1,2,3]
row2 = [4,5,6]
row3 = [7,8,9]

nums_2d = np.array([row1, row2, row3])

trace = np.trace(nums_2d)
print(trace)

15


## Excersise 3.1

**Question 1:**

Which NumPy function is used for element-wise multiplication of two matrices?

A- np.dot(matrix1, matrix2) 

B- np.multiply(matrix1, matrix2)

C- np.elementwise(matrix1, matrix2) 

D- None of the above

Answer: B


**Question 2:**

To generate an identity matrix of 4 rows and 4 columns, which of the following functions can be used?

A- np.identity(4,4)

B- np.id(4,4)

C- np.eye(4,4) 

D- All of the above

Answer: C


**Question 3:**

How to create the array of numbers 4,7,10,13,16 with NumPy: 

A- np.arange(3, 16, 3)

B- np.arange(4, 16, 3)

C- np.arange(4, 15,3) 

D- None of the above

Answer: D

## Excersise 3.2

Create a random NumPy array of 5 rows and 4 columns. Using array indexing and slicing, display the items from row 3 to end and column 2 to end.

**Solution:**

In [74]:
uniform_random = np.random.rand(4, 5)
print(uniform_random)
print("Result")
print(uniform_random[2:,3:])

[[0.72452886 0.72041584 0.04077573 0.06427304 0.50293137]
 [0.80496061 0.30012932 0.18061954 0.06908943 0.68391114]
 [0.4764706  0.94582802 0.36850443 0.83954099 0.30519222]
 [0.88190253 0.16131323 0.68356525 0.68893982 0.65417021]]
Result
[[0.83954099 0.30519222]
 [0.68893982 0.65417021]]
